
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js?v6.1.3
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
wake_on_lan:

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'
      - 'date_time_utc'
  - platform: mqtt_room
    name: "MikeWatchESP"
    device_id: "watch:mikewatch"
    state_topic: "espresense/devices/watch:mikewatch"
group: !include groups.yaml
# Storage for Bubble Card Modules
template:
  - trigger:
      - trigger: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
notify:
  - platform: group
    name: family_phones
    services:
      - service: mobile_app_kim_jong_uns_iphone
      - service: mobile_app_alexandras_iphone          
shell_command:
  shutdown_mac: '/bin/bash /config/shutdown_mac.sh'